### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by robertalanm** [Ekliptor/WolfBot#1]
Could you post your dependencies to run the project?

**Comment by Ekliptor** [comment]
thanks for your interest. I just published the main of my own dependencies: https://github.com/Ekliptor/bit-models

All my dependencies are listed in the package.json
```
    "@ekliptor/apputils": "^0.1.3",
    "@ekliptor/bintrees-local": "^1.0.6",
    "@ekliptor/bit-models": "^1.0.33",
    "@ekliptor/bitfinex-api-node-seq": "^1.1.1",
    "@ekliptor/browserutils": "^0.0.3",
    "@ekliptor/chrome-browser": "^0.0.4",
    "@ekliptor/node-bittrex-api-fix": "^0.8.2",
    "@ekliptor/packed-updater": "^1.0.4",
```
As mentioned in the README please give me a 2-4 weeks time to publish everything. This project is based on other projects i worked over the past 3 years, so I must ensure there are no references left that previous employers don't want to see on github (plus obviously my trading API keys and some private stuff).

Please stay tuned...

**Comment by Ekliptor** [comment]
The code on github is now working. All trading features are available. I also published my other modules to the npm repository.

I will add more example strategies and post a documentation of the internal Strategy API here this week: https://forum.wolfbot.org/forums/strategy-development.17/
So you can easily build your own strategies. For now you can just copy a simple strategy (such as RSI) as a starter template.

These 2 modules are still missing, which means auto software updates and social crawling + sentiment analyis is not part of the github version (yet). I will commit the social crawling plugins soon.
`
    "@ekliptor/chrome-browser": "^0.0.4",
    "@ekliptor/packed-updater": "^1.0.4",
`
Give it a try and open a new issue if you ave any questions.

**Comment by spcfran** [comment]
@Ekliptor would you mind leaving a comment on this thread once the packages are published so I get notified? Thanks!

**Comment by Ekliptor** [comment]
They are all published by now, that's why this thread has been closed. Please pull the latest master and try again.
Otherwise please open a new issue with your yarn + node version + the yarn error log

**Comment by spcfran** [comment]
The packages erroring are the ones you mentioned in your previous post (`chrome-browser` and `packed-updater`) (that's why I reused the thread), 
![image](https://user-images.githubusercontent.com/4398367/41916327-bce2e8e2-794f-11e8-9cfa-43eb2d596d34.png)
Also, npm doesn't like this package (fine with yarn, but `readme.md` says npm should work too):
`"genetic-js": "subprotocol/genetic-js#14/head",`
Also talib doesn't seem to work with Windows so the whole yarn install errors even removing the conflicting packages, but that seems to be a common issue [as described here](https://github.com/askmike/gekko/issues/732)

**Comment by Ekliptor** [comment]
Oh sorry, my mistake: I accidentally committed a version of package.json with those dependencies in it again. I fixed it. Just pull the file again and you will be able to build the bot.

About Ta-lib: yes unfortunately I also had only bad experiences building many binaries into a node using node-gyp. Yet that's the way it will be for now.
Although Windows is an easy target, the maintainers could easily release a prebuilt binary for windows. If anybody does (and maintains)t hat, I will gladly include it in WolfBot.
WolfBot will run without talib using the `--notTalib` parameter.
