### ISSUE TITLE
Building - Errors

### ISSUE THREAD

**Issue by DarkBlaez** [Ekliptor/WolfBot#100]
Just curious if this repo has been cloned locally then perform a docker-compose build and or up. The number of errors that are represented eludes to this not having been done. When was the last time this was actually done? It's quite easy, clone to a new directory, remove the docker image and perform the compose up or build. Try it and let me know what you get, until then I will have to go resolve all these issues and obviously fork with the fixes for others.

Thanks
DB

**Comment by Ekliptor** [comment]
This Docker compose image was submitted by a community member, not me. If you want to improve it feel free to do so and submit pull requests back here.

**Comment by DarkBlaez** [comment]
The docker draws from the repo so it comes down to the code. It's an issue with the code, so to claim portions are the community when it is your repo would be passing this off. When was the last time the code was cloned and built? By doing a docker-compose build it will rebuild freshly within the container. It is a good check as to the quality of the code and zero error assertions. Again, my question is, when was the last time the code was cloned and freshly built?

DB

**Comment by DarkBlaez** [comment]
Going to fork this and then resolve the issues in the forked version since I will be enhancing it

**Comment by Ekliptor** [comment]
I am not using Docker on my deployments on WolfBot org. The docker build was submitted as a Pull Request by a user a few months ago. It works for me (despite some build errors).
If you want to enhance it please feel free to do so and share your feedback and code after ;)
