### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by github-sma** [Ekliptor/WolfBot#11]
Currently having this warning:

`Error: ENOENT: no such file or directory, open '/home/sarmel/Ashdown/Ashbot/node_modules/@ekliptor/browserutils/src/js/functions.js'`

**Comment by github-sma** [comment]
[Error line](https://github.com/Ekliptor/WolfBot/blob/498e86b80feeb0e54560135598c53298b4b79f5a/src/WebSocket/BacktestingUpdater.ts#L17)

**Comment by Ekliptor** [comment]
Please ensure that you have`@ekliptor/browserutils` installed using `yarn install`
Afterwards please run the `tsc` command in the browserutils folder as mentioned in the Readme of WolfBot for all `@ekliptor/xxx` projects.

**Comment by github-sma** [comment]
Thanks. But now i am having this warning
`Error: ENOENT: no such file or directory, open '/home/sarmel/Ashdown/Ashbot/node_modules/@ekliptor/browserutils/bld-web/browserutils.js'`

**Comment by Ekliptor** [comment]
The file is part of the webpack build. You must run webpack in that folder. See webpack.config.js

**Comment by github-sma** [comment]
Ok. Thanks

**Comment by github-sma** [comment]
Why ignore this files?
`
src/Social/Crawler  
src/Social/Watcher  
config/social
`

**Comment by Ekliptor** [comment]
as mentioned in the Readme you have to use the --noBrowser parameter because these files are not (yet) part of the open source version
