### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by fractalawareness** [Ekliptor/WolfBot#12]
I've added missing **forex.analytics** dependency, created a script to run **tsc** on each @Ekliptor dependency folder with tsconfig inside (overwriting **watch** to **false**), but now facing errors about missing files.

```
src/Controller.ts:29:34 - error TS2307: Cannot find module './Social/Crawler/Telegram'.
29 import {RawTelegramMessage} from "./Social/Crawler/Telegram";
-----------
src/WebSocket/TradingViewData.ts:21:30 - error TS2307: Cannot find module '../../public/js/libs/tv                                                             /charting_library.min'.
21 import * as TradingView from "../../public/js/libs/tv/charting_library.min"
```
These folders and file are in the **.gitignore**:
```
src/Social/Crawler
src/Social/Watcher
public/js/libs/tv
src/Exchanges/BitmexFix.ts
src/Strategies/TradingViewSignal.ts
config/TradingViewSignal.json
```
Can you please remove some of these files from .gitignore and push them?

**Comment by Ekliptor** [comment]
They are not needed to run the open source version.
As stated in the readme, when you use the startup parameters `--noBrowser --noUpdate` it will run without those files

**Comment by fractalawareness** [comment]
Thanx for a quick response.
Actually I had to comment this line https://github.com/Ekliptor/WolfBot/blob/master/src/Controller.ts#L29 and change a few lines to make it not crash at startup even with the `--noBrowser` and `--noUpdate` flags.

**Comment by Ekliptor** [comment]
that line shouldn't have been there. thx. I just committed a fix
