### ISSUE TITLE
MongoDB issue

### ISSUE THREAD

**Issue by Lucky21110** [Ekliptor/WolfBot#13]
Hello,

When I try to start the bot, I got this error.

![image](https://user-images.githubusercontent.com/21016952/51192917-9c2f3f00-18b5-11e9-8fde-a83d3d058597.png)

Anyone can help me to fix it please ?

Regards

**Comment by Lucky21110** [comment]
Problem is fixed.

**Comment by jardave** [comment]
> Problem is fixed.

How?

**Comment by anbukarasi1** [comment]
how? you solve this error i also facing same issue. please give me the solution.

**Comment by anbukarasi1** [comment]
@Lucky21110 how you solve this error i also facing same issue. please give me the solution.

**Comment by TnS-hun** [comment]
Set mongoUrl to "mongodb://localhost/wolfbotdb" in configLocal.ts.
