### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by gitgitgat** [Ekliptor/WolfBot#17]
this happens with 'yarn install' (I am in the wolfbot directory):

> yarn install v1.16.0
> util.js:220
>     throw new ERR_OUT_OF_RANGE('err', 'a negative integer', err);
>     ^
> 
> RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
>     at Object.getSystemErrorName (util.js:220:11)
>     at exceptionWithHostPort (internal/errors.js:459:21)
>     at internalConnect (net.js:833:16)
>     at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:20)
>     at emitLookup (net.js:976:9)
>     at /usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:106745:29
>     at /usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:106591:25
>     at RawTask.module.exports.RawTask.call (/usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:82961:19)
>     at flush (/usr/local/Cellar/yarn/1.16.0/libexec/lib/cli.js:83043:29)
>     at processTicksAndRejections (internal/process/task_queues.js:82:9)
>

**Comment by gitgitgat** [comment]
the problem is in osx Mojave, in linux it appears to be running ok, would still like to fix it for osx

**Comment by gitgitgat** [comment]
but in linux, in step 3/4, part 5/6 the following error pops up:

`error /home/name/Github/WolfBot/node_modules/talib`

**Comment by Ekliptor** [comment]
I can't reproduce any of your errors (without more information about the versions you are using). And they are not from WolfBot.

The first error seems to be a yarn issue and the 2nd one is definitely talib issue. Please refer to their issue trackers first.
