### ISSUE TITLE
AI config?

### ISSUE THREAD

**Issue by robertalanm** [Ekliptor/WolfBot#2]
IS the AI config not released yet? Is it any different from the other example configs?

**Comment by Ekliptor** [comment]
Hello
Thx for the info. You were right, I missed to commit a lot of sample configs to github. Please look into the `/config/machine-learning` folder for somple samples of AI config.

AI still has to be integrated with trading. What it does here is

- you specify some currency pairs and indicators (including params)
- the neural network will find patterns in this input data and learn from it
- it will display price suggestions for the next candle in live mode in the "Oracle" tab

-
