### ISSUE TITLE
Error: cannot find module .../WolfBot/node_modules/@ekliptor/apputils/build/utils

### ISSUE THREAD

**Issue by gitgitgat** [Ekliptor/WolfBot#20]
The above error shows up after doing the `tsc` followed by the `node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser` command.

**Comment by gitgitgat** [comment]
build does not appear in node_modules/@ekliptor/apputils/

**Comment by Ekliptor** [comment]
it must appear in ´node_modules/@ekliptor/apputils/build/´
otherwise tsc will show you some errors which should tell you what went wrong

**Comment by gitgitgat** [comment]
tsc says cannot find module '@ekliptor/apputils' and '@ekliptor/bit-models' even though they are found in node_modules/@ekliptor

**Comment by Ekliptor** [comment]
you must run `tsc` inside the apputils etc directory too.
otherwise please try the cloud version
