### ISSUE TITLE
Error connecting to MongoDB v3.6.3

### ISSUE THREAD

**Issue by krisstox** [Ekliptor/WolfBot#21]
`error: Error connecting to MongoDB {"message":"missing delimiting slash between hosts and options","stack":"Error: missing delimiting slash between hosts and options\n    at parseConnectionString (/home/kriss/WolfBot/node_modules/mongodb/lib/url_parser.js:147:11)\n    at parseHandler (/home/kriss/WolfBot/node_modules/mongodb/lib/url_parser.js:113:14)\n    at module.exports (/home/kriss/WolfBot/node_modules/mongodb/lib/url_parser.js:98:5)\n    at connect (/home/kriss/WolfBot/node_modules/mongodb/lib/mongo_client.js:485:3)\n    at Function.MongoClient.connect (/home/kriss/WolfBot/node_modules/mongodb/lib/mongo_client.js:250:3)\n    at connect (/home/kriss/WolfBot/src/database.ts:81:17)\n    at /home/kriss/WolfBot/src/database.ts:58:13\n    at new Promise (<anonymous>)\n    at Object.connectAll (/home/kriss/WolfBot/src/database.ts:57:25)\n    at Controller.connect (/home/kriss/WolfBot/src/Controller.ts:190:12)\n    at /home/kriss/WolfBot/src/Controller.ts:100:18\n    at new Promise (<anonymous>)\n    at Controller.start (/home/kriss/WolfBot/src/Controller.ts:98:16)\n    at Object.<anonymous> (/home/kriss/WolfBot/app.ts:278:16)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:643:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:556:12)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)\n    at internal/main/run_main_module.js:17:11"}
2019-07-08 19:48:47 - info: Main process exited with code 1`

any idea?

**Comment by Ekliptor** [comment]
Your `mongoUrl` in `configLocal.ts` must be of the format `mongodb://user:password@host:port/database`
please refer to the mongo docs for details
