### ISSUE TITLE
error on fresh install : deribit-v2-ws compiling SyntaxError

### ISSUE THREAD

**Issue by Gabri** [Ekliptor/WolfBot#22]
After compiling manually some modules (as said in other issues, like apputils). When, from _build_ folder, I run:
`node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser`
I get this error:
```
/mnt/workspace/ws/git/cry/WolfBot/node_modules/deribit-v2-ws/con.js:62
  ping = async() => {
       ^
SyntaxError: Unexpected token =
(...)
```
I tried a different version of deribit-v2-ws (1.0.0 instead of 1.0.3) but a very similar error (the same but for anhoter function)

Any ideas?
Thanks

**Comment by Ekliptor** [comment]
you are runnning nodejs version older than 12. Please use the versions mentioned in the readme
