### ISSUE TITLE
MongoDB does not allow for writing on admin,local or config databases

### ISSUE THREAD

**Issue by wayjeeair** [Ekliptor/WolfBot#24]
Error message:"error: {"name":"MongoError","message":"not authorized on admin to execute command { create: \"sysMessages\", writeConcern: { w: \"majority?socketTimeoutMS\" } }","ok":0,"errmsg":"not authorized on admin to execute command { create: \"sysMessages\", writeConcern: { w: \"majority?socketTimeoutMS\" } }","code":8000,"codeName":"AtlasError"}"

Is there a way for the bot to write on the other databases on MongoDB instead of the three databases?

**Comment by Ekliptor** [comment]
look at `mongoUrl` in `configLocal.ts`
There you can define database name as part of the URL.
Please refer to Atlas or mongo docs for more details about the URL format and your error in case the problem persists.
