### ISSUE TITLE
Indicator CCI not working

### ISSUE THREAD

**Issue by ajrj** [Ekliptor/WolfBot#26]
Suggestion for the file /src/Indicators/CCI.ts
            this.valuesHigh = this.addData(this.valuesHigh, candle.close, this.params.interval);
            this.valuesLow = this.addData(this.valuesLow, candle.volume, this.params.interval);
            this.valuesClose = this.addData(this.valuesClose, candle.volume, this.params.interval);
should be 
            this.valuesHigh = this.addData(this.valuesHigh, candle.**high**, this.params.interval);
            this.valuesLow = this.addData(this.valuesLow, candle.**low**, this.params.interval);
            this.valuesClose = this.addData(this.valuesClose, candle.**close**, this.params.interval);
Tested. TALib works fine then.

**Comment by Ekliptor** [comment]
thanks. that is inded a c&p bug from another indicator... fixed
