### ISSUE TITLE
 Cannot find module '@ekliptor/bit-models'

### ISSUE THREAD

**Issue by anbukarasi1** [Ekliptor/WolfBot#27]
I tried your code but it thrown "info: ***DISCOUNT*** Having trouble setting up WolfBot on your local machine? Try the cloud version at https://wolfbot.org with a 30% discount with this code"

This logger message and it thrown  Cannot find module '@ekliptor/bit-models' this error.

Why it will happen please solve this issue as soon as possible.

**Comment by Ekliptor** [comment]
you need to run `tsc` in `@ekliptor/bit-models` and other modules from `@ekliptor/module-name` with a `tsconfig.json` in their directory. This is mentioned in the Readme.

**Comment by anbukarasi1** [comment]
thank you, now it will works.
