### ISSUE TITLE
running error 

### ISSUE THREAD

**Issue by moh7afiz90** [Ekliptor/WolfBot#31]
after running this cmd `node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser` I'm getting this error
<img width="724" alt="Screen Shot 2019-09-21 at 9 35 52 PM" src="https://user-images.githubusercontent.com/16979840/65377659-e45df700-dcb7-11e9-9d04-0cd62229daf4.png">

any idea?

**Comment by Ekliptor** [comment]
your config seems to be invalid
Idea:
1. delete any `config.json` and `configLocal.ts`
2. run `tsc` again in @ekliptor submodules such as `bit-models`
3. create a new `configLocal.ts` from the provided sample and try again

**Comment by moh7afiz90** [comment]
Alright thank you!
