### ISSUE TITLE
Bitmex fees

### ISSUE THREAD

**Issue by SpiritOfLogic** [Ekliptor/WolfBot#55]
https://github.com/Ekliptor/WolfBot/blob/7ac5f7e10ddd2d8220ab6af2cc181b2e86c0baa0/src/Exchanges/BitMEX.ts#L202

Seems as if fees for Bitmex are incorrect - https://www.bitmex.com/app/fees

**Comment by Ekliptor** [comment]
fixed with latest commit. thx

**Comment by SpiritOfLogic** [comment]
Not sure whether I understand your calculation of fees correctly but it should be 0.0075 per side as taker and -0.0025 (i.e. bonus not fee) per side as maker.

**Comment by Ekliptor** [comment]
WolfBot only has 1 fee per exchange (that value is only used for trade statistics, not for strategies). You can change it if you are always using maker/taker orders.

**Comment by SpiritOfLogic** [comment]
Ok I see - this might be an area for future improvements then - correct profit calculation especially for backtesting and also statistics similar to how the TradingView Strategy Tester does it - including draw down - would be very convenient.

**Comment by Ekliptor** [comment]
Agreed. Feel free to submit a pull request and compute fees for trading history depending on maker/taker ;)
The complicated part is finding out what amount of your orders paid which fee. For example: You submit a limit order to buy x BTC and the order gets filled 50% immediately (taker fee). The other half gets filled later (maker fee). WolfBot queries open orders to check if they are filled (and move them), but doesn't query order history to check for paid fees. So the best way to do this is adding another API call "query my order history"
