### ISSUE TITLE
Refusing to run NodeJS app as root Error

### ISSUE THREAD

**Issue by ifeLight** [Ekliptor/WolfBot#67]
root@trade9ine:\~/trader# cd build
root@trade9ine:~\/trader/build# node app.js --debug
Refusing to run NodeJS app as root
root@trade9ine:\~/trader/build# ls
ai.js      app.js.map       config.js      configLocal-sample.js      configLocal.js.map  public
ai.js.map  backfind.js      config.js.map  configLocal-sample.js.map  imports.js          src
app.js     backfind.js.map  config.json    configLocal.js             imports.js.map      tests
root@trade9ine:\~/trader/build# node app.js
Refusing to run NodeJS app as root
root@trade9ine:\~/trader/build#

**Comment by Ekliptor** [comment]
The error means exactly what it says. You should not run nodejs apps as root user in general! And my apps refuse doing so on purpose. Login as another user and you can run it.

**Comment by ifeLight** [comment]
Okay I understand better
