### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by Sascha321** [Ekliptor/WolfBot#78]
hello I tried to install WolfBot on an Ubuntu 20.04, finally when I run build / app.js nothing happens. This is how I installed everything:

> sudo apt update -y && sudo apt -y upgrade
> sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
> curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt -y install nodejs
> sudo apt -y  install gcc g++ make
> 
> sudo apt-get install gnupg -y
> wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
> sudo apt-get update
> sudo apt-get install -y mongodb-org
> sudo apt update && sudo apt install node-typescript -y
> sudo npm install -g typescript
> sudo apt-get update -y
> sudo apt-get install -y webpack
> 
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
> echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
> sudo apt update -y
> sudo apt install -y yarn
> sudo apt install --no-install-recommends yarn
> 
> sudo apt install -y git
> git clone https://github.com/Ekliptor/WolfBot
> yarn install
> build/app.js

**Comment by Ekliptor** [comment]
you have to run it with `node ...`after install. Please see the README.
