### ISSUE TITLE
CexIo

### ISSUE THREAD

**Issue by Sascha321** [Ekliptor/WolfBot#81]
Hello first, thanks for the help, the bot is now running.
I would like to add CexIo, unfortunately this is not possible because the API phrase is missing. If I do it manually in "configLocal.ts", I get the message that I have to enter an API key first.
Can you help me?

**Comment by Sascha321** [comment]
Hello, I have now found the file where I can add the exchanges.

Now I have the following problem, what does that mean?

> "Spread: Not yet enough trades for arbitrage. 3 candles"
Where the 3 is there is sometimes a 1 or a 4 or a 2.

Can someone help me there?

thank you

**Comment by Sascha321** [comment]
Hello
Somehow the bot is not working properly. Shouldn't this 0.16% be seen somewhere on my trading platform?
I stopped arbitrage and leverage.

> Margin Trading: No
> Trading balance: 0.004 BTC
> Position: long
> Amount: 0.01658885 ETH
> Profit/Loss: 0.00000650 BTC (0.16%)

**Comment by Ekliptor** [comment]
please use Discord for support questions. Github is for open source development of the bot.
WolfBot uses cross margin when trading and a leverage setting depending on your config. That's how the 0.16% is being calculated As long as the amount in BTC an ETH is correct, you are fine, see https://wolfbot.org/strategy-docs/
