### ISSUE TITLE
backtesting not run old data

### ISSUE THREAD

**Issue by jordanlanch** [Ekliptor/WolfBot#82]
I took the test by doing a 1 year test.
Once it was finished I did another backtesting with a different strategy, the mistake is that it started to download another full year.
in the mongo database is already in 10Gb and continues downloading data.
as if it did not recognize the data already downloaded

![image](https://user-images.githubusercontent.com/24902096/93936014-2961a280-fceb-11ea-9de8-d50708d6cd83.png)

![image](https://user-images.githubusercontent.com/24902096/93936090-4007f980-fceb-11ea-8a97-c9601cbd673d.png)

**Comment by Ekliptor** [comment]
this likely means your date range is wrong. Look at the `tradesHistory` collection in MongoDB to see what ranges WolfBot says he has imported and adjust your backtesting accordingly
