### ISSUE TITLE
i can't use the same data with different strategies

### ISSUE THREAD

**Issue by jordanlanch** [Ekliptor/WolfBot#84]
download the 4 months data with a strategy.
When I went to try the same data with a different strategy he started downloading it again.
and when i click on the button show currencies with fully imported history , not work.

List of currencies with completely imported history
This is a list of automatically imported currencies for backtesting. We recommend using one of the pairs here to skip the waiting time for the initial import. The history gets updated every 24h (so it will not contain the last day).

![image](https://user-images.githubusercontent.com/24902096/94105720-83ec2300-fdff-11ea-9248-dead2a7b296d.png)

**Comment by Ekliptor** [comment]
please take a look at this issue https://github.com/Ekliptor/WolfBot/issues/82
solution: `tradesHistory` collection

Also note that all "auto imported currencies" with complete history only apply to the cloud version of wolfbot. When you run it yourself you have to import trades yourself too - always.
