### ISSUE TITLE
Start parameter

### ISSUE THREAD

**Issue by Sascha321** [Ekliptor/WolfBot#96]
Hello, with this command 
"node app.js --debug --config=Noop --trader=RealTimeTrader --noUpdate --noBrowser" 
I start the Wolfbot.
What do I need to insert so that I can start the Wolfbot directly in "Trading Mode" Arbitrage.

**Comment by Ekliptor** [comment]
add `--arbitrage`
See for all available parameters https://github.com/Ekliptor/WolfBot/blob/master/app.ts

**Comment by Sascha321** [comment]
Hello, unfortunately the "--arbitrage" does not work. It still starts Trading. 
But it takes over the configuration. Here the start call.

node app.js --debug --arbitrage --config=leverage --trader=RealTimeTrader --noUpdate --noBrowser

**Comment by pardus07** [comment]
merhaba kurulum yapamıyorum bana yardımcı olabilecek birisi varmı?

**Comment by Sascha321** [comment]
Nereye kurmak istersiniz? ahududu pi'de (raspberry pi)

**Comment by pardus07** [comment]
windows 10 localhost kurulum videosu varsa izleyerek veya sıralı bir şekilde ne yapmam gerekiyor? kurulumu adım adım  anlatan bir yazı varmı ?
