### ISSUE TITLE
Start parameter

### ISSUE THREAD

**Issue by Sascha321** [Ekliptor/WolfBot#97]
Hello, unfortunately the "--arbitrage" does not work. It still starts Trading.
But it takes over the configuration. Here the start call.

node app.js --debug --arbitrage --config=leverage --trader=RealTimeTrader --noUpdate --noBrowser

**Comment by Ekliptor** [comment]
Alternatively you can:
1. open the Configuration page
2. select Trade Mode "Arbitrage"
3. Press Actions -> Restart and the bot will restart with correct start parameters for arbitrage mode
