### ISSUE TITLE
Start parameter the third

### ISSUE THREAD

**Issue by Sascha321** [Ekliptor/WolfBot#98]
Why do you keep closing the post? Is that the help you are offering?

1. do not agree with the alternative:
2.  Open the Configuration page
3.  select trade mode "Arbitrage" Press Actions -> Restart and the bot will restart with correct start parameters for arbitrage mode

I know it works myself.

I would like it to work via the call, what am I doing wrong?
node app.js --debug --arbitrage --config = leverage --trader = RealTimeTrader --noUpdate --noBrowser

**Comment by Ekliptor** [comment]
In my config it is `--arbitrage`. If that does not work please ensure your `--config=leverage` actually contains an arbitrage config (and not a trading config).

If you say my "restart bot" solution works for you, here's how you can find the correct parameters easily:
1. restart in arbitrage mode
2. check the running node processes and look at the parameters of WolfBot
3. start the bot with those parameters

**Comment by Sascha321** [comment]
I don't know how to monitor the node process.

**Comment by Ekliptor** [comment]
on unix system use `ps aux` command or on windows try a better task manager, for example https://github.com/DavidXanatos/TaskExplorer
